### ISSUE TITLE
Multiple INTU.XXXX tags causes crash

### ISSUE THREAD

**Issue by jcoliz** [jcoliz/OFXSharp#17] opened 2022-09-15 02:25 UTC
This is from @TechnicalJohn, in #15:

I recently did a download of transactions from a Discover bank account, and they include an additional INTU tag: INTU.USERID

Here's bank-banking-xml.ofx example expanded with the additional INTU.USERID tag:

```
  <SIGNONMSGSRSV1>
    <SONRS>
      <STATUS>
        <CODE>0</CODE>
        <SEVERITY>INFO</SEVERITY>
      </STATUS>
      <DTSERVER>20220812022343.143</DTSERVER>
      <LANGUAGE>ENG</LANGUAGE>
      <FI>
        <ORG>Bank of Banking</ORG>
        <FID>1234</FID>
      </FI>
      <INTU.BID>1234</INTU.BID>
      <INTU.USERID>DISCBANK9876-X-4321</INTU.USERID>
    </SONRS>
  </SIGNONMSGSRSV1>

```

This caused OFXSharp to fall into an exception because the code was assuming there would only be a single INTU node. So I adjusted the sign on method to simply get the first child node.

**Comment by jcoliz** [comment] 2022-09-15 02:39
@TechnicalJohn, I committed a test case change in an attempt to reproduce this. I couldn't reproduce it. Could you have a look at the Issue17 test, and see if you can get that to fail? Then we can work on a fix.

**Comment by TechnicalJohn** [comment] 2022-09-15 17:20
@jcoliz 
My apologies! I got things messed up in my testing and didn't get this documented correctly...

The issue is with OFX 1.0 without closing tags... Add the INTU items just below the <FI> tags to the test file secondluddite.ofx then the test will fail:
```
	<SIGNONMSGSRSV1>
		<SONRS>
			<STATUS>
				<CODE>0
				<SEVERITY>INFO
			</STATUS>
			<DTSERVER>20190308023101.862
			<LANGUAGE>ENG
			<FI>
				<ORG>Second Luddite Federal Credit Union
				<FID>9999
			</FI>
			<INTU.BID>1234
			<INTU.USERID>USER12345
		</SONRS>
	</SIGNONMSGSRSV1>
```

And then my proposed change does fix this.

**Closed** 2022-09-20 00:18 UTC
Labels: bug

**Comment by jcoliz** [comment] 2022-09-20 00:20
@TechnicalJohn Committed a fix for this. I think this is the correct fix. Problem is that the SGML-to-XML conversion didn't know where to put INTU.USERID in the resulting XML tree. Please let me know if any concerns.
